language: node_js
node_js:
  - "node"
  - "7"
before_install: cd src
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
install:
  - npm install 
script:
  - node ./node_modules/jest/bin/jest.js --watchAll