language: node_js
node_js:
 - "10.15.1"
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
before_script:
  - cd src
before_install:
  - npm i -g npm@6.4.1
install:
  - npm install
cache: npm
script:
  - npm run test

