language: node_js
node_js:
  - "node"
  - "7"
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
install:
  - npm install 
script:
  - npm run test
notifications:
  slack:
    rooms:
      - nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt#group_wcfind
